<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Réservation - SkillShare</title>
    @vite (['resources/css/style.css'])
    @vite(['resources/css/header.css'])
    @vite (['resources/css/booking.css'])
</head>
<body>
@include('includes.header')

    <main class="main-content">
        <div class="booking-container">
            <div class="booking-header">
                <h1>Réserver une session</h1>
                <p>Planifiez une session d'apprentissage avec un autre étudiant</p>
            </div>
            
            <div class="booking-content">
                <div class="booking-calendar">
                    <div class="calendar-header">
                        <button class="calendar-nav prev">◀</button>
                        <h3>Juin 2023</h3>
                        <button class="calendar-nav next">▶</button>
                    </div>
                    <div class="calendar-weekdays">
                        <span>Lun</span>
                        <span>Mar</span>
                        <span>Mer</span>
                        <span>Jeu</span>
                        <span>Ven</span>
                        <span>Sam</span>
                        <span>Dim</span>
                    </div>
                    <div class="calendar-days">
                        <!-- Calendar will be generated by JS -->
                    </div>
                </div>
                
                <div class="booking-time-slots">
                
                    <div class="user-card">
                        <div class="user-details">
                            <h2>Sophie Martin</h2>
                            <p class="user-campus">Campus de Paris</p>
                            <div class="user-rating">
                                <span class="stars">★★★★★</span>
                                <span class="rating-value">5.0</span>
                                <span class="rating-count">(15 avis)</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="skill-selection">
                        <h3>Compétence à apprendre</h3>
                        <div class="skill-options">
                            <label class="skill-option">
                                <input type="radio" name="skill" value="javascript" checked>
                                <span class="skill-name">JavaScript</span>
                            </label>
                            <label class="skill-option">
                                <input type="radio" name="skill" value="react">
                                <span class="skill-name">React</span>
                            </label>
                            <label class="skill-option">
                                <input type="radio" name="skill" value="nodejs">
                                <span class="skill-name">Node.js</span>
                            </label>
                        </div>
                    </div>
                </div>
                
                <div class="booking-details">
                    <h3>Détails de la session</h3>
                    <form id="booking-form">
                    <div class="form-group">
                        <label for="location">Lieu</label>
                        <select id="location" required>
                            <option value="">Sélectionnez un lieu</option>
                            <option value="présentiel">présentiel</option>
                            <option value="google meet">google meet</option>
                            <option value="zome">zome</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description">Lien ou l'adresse</label>
                        <textarea id="description" placeholder="Ce champ est obligatoire : veuillez indiquer le lien de la réunion ou l'adresse du lieu."></textarea>
                    </div>
                </form>
                </div>
                
                <div class="booking-summary">
                    <h3>Récapitulatif</h3>
                    <div class="summary-details">
                        <div class="summary-item">
                            <span class="summary-label">Compétence</span>
                            <span class="summary-value">JavaScript</span>
                        </div>
                        <div class="summary-item">
                            <span class="summary-label">Date</span>
                            <span class="summary-value">Mardi, 6 juin 2023</span>
                        </div>
                        <div class="summary-item">
                            <span class="summary-label">Heure</span>
                            <span class="summary-value">14:30 - 16:00</span>
                        </div>
                        <div class="summary-item">
                            <span class="summary-label">Lieu</span>
                            <span class="summary-value">À sélectionner</span>
                        </div>
                    </div>
                    <div class="booking-actions">
                        <button class="btn btn-secondary">Annuler</button>
                        <button class="btn btn-primary" id="confirm-booking-btn">Confirmer la réservation</button>
                    </div>
                </div>
            </div>
        </div>
    </main>

    @include('includes.footer')
    @vite (['resources/js/main.js'])
    @vite(['resources/js/booking.js'])

</body>
</html>

